login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.iniciar_sesion, name='iniciar_sesion'),
    path('cerrar', views.cerrar_sesion, name='cerrar_sesion'),
]

scatuaz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trabajador/', include('trabajador.urls')),
    path('usuario/', include('usuario.urls')),
    path('', include('login.urls')),
]

usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lista_usuario, name='lista_usuario'),
    path('agregar', views.agregar_usuario, name='agregar_usuario'),
    path('eliminar/<int:id>', views.eliminar_usuario, name='eliminar_usuario'),
    path('modificar/<int:id>', views.modificar_usuario, name='modificar_usuario'),
    path('cambiar/<int:id>', views.cambiar_contrasena, name='cambiar_contrasena'),
]

usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User

class UsuarioForm(UserCreationForm):

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        max_length=50,
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo es obligatorio',
            'max_length': 'La longitud maxima es de 50',
        },
        label="Correo"
    )

    password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Escribe la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Contraseña"
    )

    password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repite la contraseña',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita contraseña"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'is_superuser']

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'Las contraseñas no coinciden',
                code='password_mismatch',
            )
        return password2

class CambiarContrasenaForm(SetPasswordForm):

    new_password1 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Nueva Contraseña"
    )

    new_password2 = forms.CharField(
        max_length=16,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Repita Nueva Contraseña es obligatorio',
            'max_length': 'La longitud maxima es de 16',
            'min_length': 'La longitud minima es de 8',
        },
        label="Repita Nueva contraseña"
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

class ModificarUsuarioForm(UserChangeForm):

    username = forms.CharField(
        max_length=50,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Escribe el usuario',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Usuario es obligatorio',
            'max_length': 'La longitud maxima es de 50',
            'min_length': 'La longitud minima es de 5',
        },
        label="Usuario"
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Escribe el correo',
                'class': 'form-control form-control-sm'
            }
        ),
        error_messages={
            'required': 'El campo Correo es obligatorio',
        },
        label="Correo"
    )

    is_superuser = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input'
            }
        ),
        label="¿El usuario sera administrador?"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'is_superuser']

    def save(self, commit=True):
        user = super(ModificarUsuarioForm, self).save(commit=False)
        if commit:
            user.save()
        return user

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import UsuarioForm, CambiarContrasenaForm, ModificarUsuarioForm
from django.contrib.auth import login, authenticate

# Create your views here.

@login_required
def lista_usuario(request):
    if request.user.is_superuser:
        usuarios = User.objects.all()
        context = {
            'usuarios': usuarios,
        }
        return render(request, 'lista_usuario.html', context)
    return redirect('lista_trabajador')


@login_required
def agregar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_usuario')
    else:
        form = UsuarioForm()
    return render(request, 'agregar_usuario.html', {'form':form})

@login_required
def eliminar_usuario(request, id):
    if request.method == 'POST':
        usuario = User.objects.get(pk=id)
        usuario.delete()
        return redirect('lista_usuario')
    else:
        usuario = User.objects.get(pk=id)
        return render(request, 'confirm_delete_user.html', {'usuario': usuario})

@login_required
def modificar_usuario(request, id):
    usuario = User.objects.get(pk=id)
    if request.method == 'POST':
        form = ModificarUsuarioForm(request.POST, instance=usuario) 
        if form.is_valid():
            form.save()
            return redirect('lista_usuario')
    else:
        form = ModificarUsuarioForm(instance=usuario)
    return render(request, 'modificar_usuario.html', {'form':form, 'usuario':usuario})

@login_required
def cambiar_contrasena(request, id):
    usuario = User.objects.get(pk=id)
    if request.method == 'POST':
        form = CambiarContrasenaForm(usuario, data=request.POST) 
        if form.is_valid():
            form.clean_new_password2()
            form.save()
            return redirect('lista_usuario')
    else:
        form = CambiarContrasenaForm(usuario)
    return render(request, 'cambiar_contrasena.html', {'form':form, 'usuario':usuario})

usuario/templates/agregar_usuario.html
{% extends 'base.html' %}

{% block contenido %}

<form method="post" class="form pt-3">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <ul class = 'form-errors list-unstyled'>
            {% for error in form.non_field_errors %}
                <li class = "text-danger"> {{error}} </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-md-6">

            <div class="row mb-2">
                <div class="col">
                    <h1 class="card-title mb-0">Nuevo Usuario</h1>
                    <p class="text-info">Todos los campos con asterisco son obligatorio</p>
                </div>
            </div>

            <div class="card mb-3 shadow">
                <div class="card-header mb-3">
                    <h4 class="card-title mb-0">Datos</h4>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-11">
                        <label for="id_username">
                            *{{form.username.label}}
                        </label>
                        {{form.username}}
                        {% for error in form.username.errors %}
                            <p class="text-danger text-center pb-0 mb-0">
                                {{error}}
                            </p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-11">
                        <label for="id_email">
                            *{{form.email.label}}
                        </label>
                        {{form.email}}
                        {% for error in form.email.errors %}
                            <p class="text-danger text-center pb-0 mb-0">
                                {{error}}
                            </p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-11">
                        <label for="id_password1">
                            *{{form.password1.label}}
                        </label>
                        {{form.password1}}
                        {% for error in form.password1.errors %}
                            <p class="text-danger text-center pb-0 mb-0">
                                {{error}}
                            </p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-11">
                        <label for="id_password2">
                            *{{form.password2.label}}
                        </label>
                        {{form.password2}}
                        {% for error in form.password2.errors %}
                            <p class="text-danger text-center pb-0 mb-0">
                                {{error}}
                            </p>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row justify-content-center">
                    <div class="col-11">
                        <div class="form-inline justify-content-center mb-3 mt-1">
                            {{form.is_superuser}}
                            <label class="form-check-label text-primary" for="id_is_superuser">
                                {{form.is_superuser.label}}
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex flex-row-reverse mb-3">
                <a href="{% url "lista_usuario" %}" class="btn btn-secondary ml-2">Cancelar</a>
                <button type="submit" class="btn btn-primary">Agregar</button>
            </div>
        </div>
    </div>

</form>

{% endblock contenido %}

usuario/templates/cambiar_contrasena.html
{% extends 'base.html' %}

{% block contenido %}

        <form method="post" class="form pt-4">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-5">

                    <div class="row">
                        <div class="col">
                            <h1 class="card-title">Cambiar Contraseña</h1>
                        </div>
                    </div>
        
        
                    <div class="card mb-3 shadow">
                            <div class="card-header">
                                    <h4 class="card-title mb-0">Datos</h4>
                                </div>
                        <div class="card-body">
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_new_password1">
                                        {{form.new_password1.label}}
                                    </label>
                                    {{form.new_password1}}
                                    {% for error in form.new_password1.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_new_password2">
                                        {{form.new_password2.label}}
                                    </label>
                                    {{form.new_password2}}
                                    {% for error in form.new_password2.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
        
                    <div class="d-flex flex-row-reverse">
                        <a href="{% url "modificar_usuario" usuario.id %}" class="btn btn-secondary ml-2">Cancelar</a>
                        <button type="submit" class="btn btn-primary">Actualizar</button>
                    </div>
                </div>
            </div>

        </form>

{% endblock contenido %}

usuario/templates/confirm_delete_user.html
{% extends 'base.html' %}

{% block contenido %}
<div class="row justify-content-center">
    <div class="card col-6 space shadow">
        <div class="card-body">
            <div class="text-center">
                {% if user.get_username == usuario.username %}
                    <h3 class="resaltar text-center d-inline-block mb-4">
                        ¡CUIDADO! Estas por borrar tu propia cuenta
                    </h3>
                {% endif %}
                <h3 class="text-center d-inline">
                    ¿Seguro que deseas eliminar al usuario 
                </h3>
                <h3 class="resaltar text-center d-inline-block">
                    {{ usuario.username }}
                </h3>
                <h3 class="text-center d-inline">
                    ?
                </h3>
            </div>
            <form method="post" class="form">
                {% csrf_token %}
                <div class="d-flex justify-content-end pt-4">
                    <input type="submit" value="Eliminar" class="btn btn-danger mr-2">
                    <button
                        onClick="javascript:history.go(-1);"
                        class="btn btn-secondary"
                    >
                        Regresar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}
    

usuario/templates/lista_usuario.html
{% extends 'base.html' %}

{% block contenido %}

<div class="row pt-5 justify-content-center">
    <div class="col-10">
        <h1>Lista de Usuarios</h1>
    </div>
    <div class="col-10 align-self-end">
        <a href="{% url "agregar_usuario" %}" class="btn btn-success bt-sm float-right">Agregar Usuario</a>
    </div>
</div>
<div class="row mt-3 justify-content-center">
    <div class="col-10">
        {% if usuarios|length == 0 %}
            <h4>No hay usuarios</h4>
        {% else %}
            <table class="table table-dark rounded-lg shadow">
                <thead class="thead-dark">
                    <th>Usuario</th>
                    <th>Email</th>
                    <th class="text-center">Admin</th>
                    <th class="text-center">Opciones</th>
                </thead>
                <tbody>

                    {% for usuario in usuarios %}
                        <tr>
                            <td>{{usuario.username}}</td>
                            <td>{{usuario.email}}</td>
                            <td class="text-center">
                                <input type="checkbox" id="id_is_superuser" disabled
                                    {% if usuario.is_superuser == 1 %}
                                      checked
                                    {% endif %}
                                >
                            </td>
                            <td class="text-center">
                                <a href="{% url "eliminar_usuario" usuario.id %}" class="btn btn-danger btn-sm mr-4">Eliminar</a>
                                <a href="{% url "modificar_usuario" usuario.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        {% endif %}
    </div>
</div>

{% endblock contenido %}

usuario/templates/modificar_usuario.html
{% extends 'base.html' %}

{% block contenido %}

        <form method="post" class="form pt-4">
            {% csrf_token %}
            <div class="row justify-content-center">
                <div class="col-6">

                    <div class="row">
                        <div class="col">
                            <h1 class="card-title">Modificar Usuario</h1>
                        </div>
                    </div>
        
        
                    <div class="card mb-3 shadow">
                        <div class="card-header">
                            <h4 class="card-title mb-0">Datos</h4>
                        </div>
                        <div class="card-body pb-0">
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_username">
                                        {{form.username.label}}
                                    </label>
                                    {{form.username}}
                                    {% for error in form.username.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <label for="id_email">
                                        {{form.email.label}}
                                    </label>
                                    {{form.email}}
                                    {% for error in form.email.errors %}
                                        <p class="text-danger text-center">
                                            {{error}}
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-11">
                                    <div class="form-inline justify-content-center">
                                        {{form.is_superuser}}
                                        <label class="form-check-label text-primary" for="id_is_superuser">
                                            {{form.is_superuser.label}}
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row justify-content-center mb-3">
                                <a href="{% url "cambiar_contrasena" usuario.id %}">Cambiar contraseña</a>
                            </div>
                        </div>
                    </div>
        
                    <div class="d-flex flex-row-reverse">
                        <a href="{% url "lista_usuario" %}" class="btn btn-secondary ml-2">Cancelar</a>
                        <button type="submit" class="btn btn-primary">Actualizar</button>
                    </div>
                </div>
            </div>

        </form>

{% endblock contenido %}